### ISSUE TITLE
mta.yaml module bookshop-db type: hdb - probably incorrect

### ISSUE THREAD

**Issue by techaware** [SAP-samples/cloud-cap-nodejs-codejam#17]
In exercise 9, mta.yaml has type: hdb for module bookshop-db. Is this the correct type? When I deploy it to CF, it throws an error - buildpack not found. 
Documentation of mta.yaml has only following types for HDI: 
MTA Deployment Descriptor Modules Keys [documentation](https://help.sap.com/viewer/4505d0bdaf4948449b7f7379d24d0f0d/2.0.03/en-US/4050fee4c469498ebc31b10f2ae15ff2.html#loio4050fee4c469498ebc31b10f2ae15ff2__table_sj5_vdb_kv) has only following values for Type property: 

com.sap.xs.hdi
com.sap.xs.hdi-dynamic
com.sap.xs.hdi-zdm

Do we have to use one of these values for HDI module? Please confirm. 
Thanks in advance.

**Comment by IObert** [comment]
Hi @techaware,

yes, it is the correct type. I'm afraid the error originates from another issue.
I'll close this issue now, please reopen it if needed (or if you have additional questions)
